import os
from groq import Groq

api_key = os.getenv('GROQ_API_KEY')
if not api_key or api_key == "your_groq_api_key_here":
    client = None
else:
    try:
        client = Groq(api_key=api_key)
    except Exception as e:
        client = None

def detect_ai_text(text):
    """Detect if text is generated by AI"""
    if not client:
        return "API key not configured. Please set GROQ_API_KEY."
    prompt = f"Analyze the following text and determine if it was generated by AI. Respond with 'AI-generated' or 'Human-written' and a brief explanation.\n\nText: {text}"
    response = client.chat.completions.create(
        model="mixtral-8x7b-32768",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=100
    )
    return response.choices[0].message.content.strip()

def summarize_text(text):
    """Generate a concise summary of the text"""
    if not client:
        return "API key not configured. Please set GROQ_API_KEY."
    prompt = f"Summarize the following text in a concise manner:\n\n{text}"
    response = client.chat.completions.create(
        model="mixtral-8x7b-32768",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=150
    )
    return response.choices[0].message.content.strip()

def rewrite_text(text):
    """Rewrite the text in a natural way"""
    if not client:
        return "API key not configured. Please set GROQ_API_KEY."
    prompt = f"Rewrite the following text in a more natural and engaging way:\n\n{text}"
    response = client.chat.completions.create(
        model="mixtral-8x7b-32768",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=300
    )
    return response.choices[0].message.content.strip()